<?xml version="1.0" encoding="utf-8"?><Database Name="QLNHANVIEN" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-MEFCVV0Q\SQLEXPRESS;Initial Catalog=QLNHANVIEN;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="QuanLyNhanVien.Properties.Settings" SettingsPropertyName="QLNHANVIENConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DEAN" Member="DEANs">
    <Type Name="DEAN">
      <Column Name="MaDeAn" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDeAn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Ng_BatDauDeAn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Ng_KetThucDean" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DEAN_PHANCONG" Member="PHANCONGs" ThisKey="MaDeAn" OtherKey="MaDeAn" Type="PHANCONG" />
      <Association Name="PHONGBAN_DEAN" Member="PHONGBAN" ThisKey="MaPhong" OtherKey="MaPhg" Type="PHONGBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OTPDateSend" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OTPCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateActive" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LeaveID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RandomKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenNV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="dchi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaTrgPhong" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_PHANCONG" Member="PHANCONGs" ThisKey="MaNV" OtherKey="MaNV" Type="PHANCONG" />
      <Association Name="PHONGBAN_NHANVIEN" Member="PHONGBAN" ThisKey="MaPhong" OtherKey="MaPhg" Type="PHONGBAN" IsForeignKey="true" />
      <Association Name="PHONGBAN_NHANVIEN1" Member="PHONGBAN1" ThisKey="MaTrgPhong" OtherKey="MaTrgPhong" Type="PHONGBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANCONG" Member="PHANCONGs">
    <Type Name="PHANCONG">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDeAn" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DEAN_PHANCONG" Member="DEAN" ThisKey="MaDeAn" OtherKey="MaDeAn" Type="DEAN" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHANCONG" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN" Member="PHONGBANs">
    <Type Name="PHONGBAN">
      <Column Name="MaPhg" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTrgPhong" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhg" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenTrgPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PHONGBAN_DEAN" Member="DEANs" ThisKey="MaPhg" OtherKey="MaPhong" Type="DEAN" />
      <Association Name="PHONGBAN_NHANVIEN" Member="NHANVIENs" ThisKey="MaPhg" OtherKey="MaPhong" Type="NHANVIEN" />
      <Association Name="PHONGBAN_NHANVIEN1" Member="NHANVIENs1" ThisKey="MaTrgPhong" OtherKey="MaTrgPhong" Type="NHANVIEN" />
    </Type>
  </Table>
</Database>